### ISSUE TITLE
Public API Status

### ISSUE THREAD

**Issue by Code-DNL** [evilarceus/Spotify-PlayCount#11]
Im not sure if Spotify changed anything, but for some reason the public api just isnt working rn

**Comment by entriphy** [comment]
It works now. Had to temporarily shut down the server due to too many requests per second.

**Comment by ponzilover** [comment]
It doesn't work now.

**Comment by ponzilover** [comment]
Hello @evilarceus , I read that you had to shut down the public API service.
It was really useful to me and to other people, so I'd like to help you keep it up.
I'm ready to pay my share!

**Comment by Chartmastersorg** [comment]
Same here. My website is surely the main reason why your server got this amount of requests, it's a key functionality for chart fans using it. I've been able to do the complete installation at my end with no issue, someway I'm failing the usage part, although I used your own API for quite some time. 

With a bit of assistance from you, I would be able to run it, and to pay for it. It's just a too good of an API to have it offline. Ping me back if this sounds fair to you!

**Comment by john833** [comment]
I'm also willing to pay to use the API.

**Comment by TheMusic25** [comment]
Hey! I have a YouTube Channel about music. I make charts. And I saw yesterday this Api about knowing all the streams of an album. And I am interested. I'd be very grateful if you could pass me the code or the api. Maybe I can return you the favor. Is there any way that we can talk? Thank you so much. TheMusic25.

**Comment by john833** [comment]
Around $30 a month per person would be an ok price I think.

**Comment by btsgraphs** [comment]
@evilarceus 

Please reconsider hosting this API publicly because it's a unique tool and it saves us so much time. My friend and I used to track BTS songs manually (every day for over 8 months) and now we're back at it again. Maybe you can create a pricing plan based on usage. DM me @/bts_graphs on twitter to talk about prices. Thanks for your time.

**Comment by Chartmastersorg** [comment]
Sorry for the longer than expected time (I became a father last week :)), but there is no reason to worry about the API disappearing. 

I have it up and running locally, during the upcoming days I'll deal with my server provider to host the search engine I developed and which uses evilarceus' fantastic API, and then i'll connect it to my website. This work won't be lost.

**Comment by btsgraphs** [comment]
Congrats!!! 

I have never tried your site; I was actually talking about my glitch app btsgraphs.glitch.me that runs on evilarceus' API.

**Comment by entriphy** [comment]
Sorry for not responding for a while. I didn't want to give a definite answer since I wasn't sure if I wanted to make users pay to use the API (having others pay for access to data that I don't own... just doesn't sit right with me :P)

Anyway, I've been looking at other Spotify-related projects and noticed that [librespot-java](https://github.com/librespot-org/librespot-java) has a way to use the Hermes protocol, which is what Spotify uses for retrieving play counts and other desktop-specific data. I've forked it and changed it so that it can work similarly to this project, and it has much lower CPU and memory usage. Here's the repository:  [sp-playcount-librespot](https://github.com/evilarceus/sp-playcount-librespot).
Oh, and it doesn't require the Spotify desktop client, meaning it's much easier to deploy 😄

I'm also hosting the API once again, see the sp-playcount-librespot repository for info. I'm currently trying out Heroku for hosting, but I might move it if any issues arise. The API response is also much different, so you'll have to rewrite much of your code. This won't happen again for future versions unless Spotify changes something on their end.

This repository will be archived until I rewrite sp-playcount-librespot in a different language (not a fan of maintaining Java code lol).
